routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','frontend\DesignController@index')->name('index');
Route::get('/services','frontend\DesignController@services')->name('services');
Route::get('/car', 'frontend\DesignController@cars')->name('cars');
Route::get('/about', 'frontend\DesignController@about')->name('about');
/*Route::get('/blog', function () {return view('frontend.pages.blog');})->name('blog');*/
Route::get('/single', function () {return view('frontend.pages.single');})->name('single');
Route::get('/contact/{id?}', 'frontend\DesignController@contact')->name('contact');
Route::post('/contact/store', 'frontend\DesignController@contactStore')->name('client.store');
Route::post('/get/cars', 'frontend\DesignController@getCars')->name('get.cars');
Route::get('admin', 'Auth\LoginController@showLoginForm');
Route::post('admin', 'Auth\LoginController@login');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'AuthenticateUser','namespace'=>'backend','prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/dashboard','HomeController@index')->name('dashboard');
    Route::get('/cars/manage','CarsController@index')->name('cars.manage');
    Route::get('/cars/add','CarsController@create')->name('cars.add');
    Route::post('/cars/store','CarsController@store')->name('cars.store');
    Route::post('/cars/delete/{id}','CarsController@destroy')->name('cars.delete');
    Route::get('/cars/edit/{id}','CarsController@edit')->name('cars.edit');
    Route::get('/cars/get/','ClientController@index')->name('get.clients');
    Route::get('/cars/show/{id}','ClientController@show')->name('get.show');

    Route::get('/cms/about','CmsController@index')->name('cms.about');
    Route::get('/cms/about/add','CmsController@create')->name('cms.add');
    Route::post('/cms/about/store','CmsController@store')->name('cms.store');
    Route::get('/cms/about/edit/{id}','CmsController@edit')->name('cms.edit');
    Route::post('/cms/about/delete/{id}','CmsController@destroy')->name('cms.delete');

    Route::get('/cms/service','CmsController@serviceindex')->name('cms.service');
    Route::get('/cms/service/add','CmsController@servicecreate')->name('cms.service.add');
    Route::post('/cms/service/store','CmsController@servicestore')->name('cms.service.store');
    Route::get('/cms/service/edit/{id}','CmsController@serviceedit')->name('cms.service.edit');
    Route::post('/cms/service/delete/{id}','CmsController@servicedestroy')->name('cms.service.delete');

    Route::get('/cms/contact','CmsController@contactindex')->name('cms.contact');
    Route::get('/cms/contact/add','CmsController@contactcreate')->name('cms.contact.add');
    Route::post('/cms/contact/store','CmsController@contactstore')->name('cms.contact.store');
    Route::get('/cms/contact/edit/{id}','CmsController@contactedit')->name('cms.contact.edit');
    Route::post('/cms/contact/delete/{id}','CmsController@contactdestroy')->name('cms.contact.delete');

    Route::get('/seo','SeoController@index')->name('seo');
    Route::get('/seo/add','SeoController@create')->name('seo.add');
    Route::post('/seo/store','SeoController@store')->name('seo.store');
    Route::get('/seo/edit/{id}','SeoController@edit')->name('seo.edit');
    Route::post('/seo/delete/{id}','SeoController@destroy')->name('seo.delete');

    Route::get('/review/manage','ReviewController@index')->name('review');
    Route::get('/review/add','ReviewController@create')->name('review.add');
    Route::post('/review/store','ReviewController@store')->name('review.store');
    Route::post('/review/delete/{id}','ReviewController@destroy')->name('review.delete');
    Route::get('/review/edit/{id}','ReviewController@edit')->name('review.edit');
   
});

app/Http/Controllers/backend/ReviewController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\backend\Review;
use Illuminate\Support\Facades\File;


class ReviewController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $review = Review::get();
        return view('backend.modules.review.index')->with(compact('review'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.modules.review.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
       
        if(isset($request->editid)){
            $request->validate([
                'name' => 'required',
                'desc'=> 'required',
            ]);
            $obj = Review::findorfail($request->editid);
        }else{
            $request->validate([
                'name' => 'required',
                'desc'=> 'required',
            ]);
            $obj = new Review();
        }
        if($request->file('image') != null){
            $ext = $request->file('image')->getClientOriginalExtension();
            $file = $request->file('image');
            $path = md5($file->getClientOriginalName() . time()) . "." . $ext;
            $file->move(public_path('review'), $path);
        }
        if(isset($request->editid)){
            if($request->file('image1') != null){
                $image_path = public_path('review')."/".$obj->image;  // Value is not URL but directory file path
                if(File::exists($image_path)) {
                    File::delete($image_path);
                }
                $ext = $request->file('image1')->getClientOriginalExtension();
                $file = $request->file('image1');
                $path = md5($file->getClientOriginalName() . time()) . "." . $ext;
                $file->move(public_path('review'), $path);
            }
        }

        $obj->name = $request['name'];
        $obj->desc = $request['desc'];
      
        if(isset($path))
            $obj->image = $path;

        $obj->save();

        if(isset($request->editid))
            toastr()->info('Data has been Updated successfully!');
        else
            toastr()->success('Data has been saved successfully!');


        return redirect()->route('admin.review');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $review = Review::where('id',$id)->get();
        return view('backend.modules.review.edit')->with(compact('review'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Review::where('id',$id)->delete();
        return response()->json(1);
    }
}

resources/views/backend/modules/review/add.blade.php
@include('backend.modules.layout.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Car Review Form
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Review</li>
            <li class="active"><a href="{{route('admin.review.add')}}">Add Review</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Enter Details Of The Review</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form id="reviewForm" enctype="multipart/form-data" action="{{route('admin.review.store')}}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-md-6 unique">
                                <label>Name:</label>
                                <input type="text" id="name" class="form-control" name="name"
                                       placeholder="Name*:"
                                       value="{{old('name')}}">
                                @if($errors->has('name'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-md-6 unique">
                                <label>Description:</label>
                                <input type="text" id="desc" class="form-control" name="desc"
                                       placeholder="Description*:"
                                       value="{{old('desc')}}">
                                @if($errors->has('desc'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('desc') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 unique">
                                <label>Image:</label>
                                <input type="file" id="image" onchange="readURL(this);" class="form-control" name="image">
                            </div>
                           
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 unique">
                                <img src="" id="img" style="        width: auto;
    height: auto;">
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Add Review</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@include('backend.modules.layout.foot')
@include('backend.modules.review.script')
<style>
    .error{
        color:red;
    }
</style>

resources/views/backend/modules/review/edit.blade.php
@include('backend.modules.layout.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Review Update Form
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Review</li>
            <li class="active"><a onclick="location.reload()" style="cursor: pointer">Add Review</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-md-10">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Enter Details Of The Review</h3>
                </div>
                <!--================================ /.box-header =================================================-->
                <!--================================ form start ==================================================-->
                <form id="reviewForm" enctype="multipart/form-data" action="{{route('admin.review.store')}}" method="post">
                
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-md-6 unique">
                                <label>Name:</label>
                                <input type="hidden" name="editid" value="{{$review[0]->id}}"></input>
                                <input type="text" id="name" class="form-control" name="name"
                                       placeholder="Name*:"
                                       value="{{old('name') ? old('name') : ( ($review[0]->name) ? $review[0]->name : '' )}}">
                                @if($errors->has('name'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-6 unique">
                                <label>Description:</label>
                               <input type="text" id="desc" class="form-control" name="desc"
                                       placeholder="Description*:"
                                       value="{{old('desc') ? old('desc') : ( ($review[0]->desc) ? $review[0]->desc : '' )}}">
                                @if($errors->has('desc'))
                                    <span id="invalid-feedback" role="alert">
                                        <strong id="error" style="color: red">{{ $errors->first('desc') }}</strong>
                                    </span>
                                @endif
                            </div>
                           
                        </div>
                        <div class="form-group">
                            
                            <div class="col-md-6 unique">
                                <label>Image:</label>
                                <input type="file" id="image" onchange="readURL(this);" class="form-control" name="image1">
                            </div>
                   
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 unique">
                                <img src="{{asset('review')}}\{{$review[0]->image}}" id="img">
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Update Review</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@include('backend.modules.layout.foot')
@include('backend.modules.review.script')

resources/views/backend/modules/review/index.blade.php
@include('backend.modules.layout.app')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            &nbsp;&nbsp;&nbsp;Review
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Review</li>
            <li class="active"><a href="{{route('admin.review')}}">Manage Review</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="col-lg-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">List Of All Review </h3>
                    <a class="btn btn-primary pull-right" href="{{route('admin.review.add')}}">
                        <i class="glyphicon glyphicon-plus"></i>
                        Add New Review
                    </a>
                </div>
                <div class="box-body">
                    <div class="table-responsive data-table-wrapper">
                        <table id="example" class="ui celled table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($review as $k=> $data)
                                <tr>
                                    <td>{{$data->id}}</td>
                                    <td>{{$data->name}}</td>
                                   
                                    <td>{{$data->desc}}</td>
                                    <td style="text-align: center;"> <img style="width: 70px;border-radius: 100px;" src="<?php echo asset("review/$data->image")?>"></img>

                                   
                                    <td>
                                        <a style="color: green;font-size: x-large;cursor: pointer;" href="{{route('admin.review.edit',$data->id)}}">
                                            <i class="fa fa-edit"></i>
                                        </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <a style="color: red;font-size: x-large;cursor: pointer;" onclick="deleteCar({{$data->id}})" data-id="{{$data->id}}">
                                            <i class="fa fa-trash"></i>
                                        </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div><!-- /.box-body -->
            </div>
        </div>
    </section>
</div>
@jquery
@toastr_js
@toastr_render
@include('backend.modules.layout.foot')
@include('backend.modules.review.script')
<script>
    $(document).ready(function() {
        var table = $('#example').DataTable( {
            lengthChange: false,
        } );
    } );
</script>

resources/views/backend/modules/review/script.blade.php
<script>
    function readURL(input) {
        var abc = $('#image').val();
        var fileExtension = ['jpeg', 'jpg', 'png'];
        var abc1 = abc.split('.').pop().toLowerCase();
        var reader = new FileReader();
        if($.inArray(abc1,fileExtension) !== -1)
        {
            $('#image-error').hide();
            if (input.files && input.files[0]) {
                reader.onload = function (e) {
                    $('#img')
                        .attr('src', e.target.result)
                        .width(auto)
                        .height(auto);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        else
        {
            if (input.files && input.files[0]) {
                reader.onload = function (e) {
                    $('#img')
                        .attr('src', '#')
                        .width(0)
                        .height(0);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    }
</script>
<script>
    $(document).ready(function () {
        $("#reviewForm").validate({
            rules:{
                name:{
                    required:true,
                },
                desc:{
                    required:true,
                },
             
                image:{
                    required:true,
                    extension: "png|jpeg|jpg",
                    accept: "image/jpg,image/jpeg,image/png,image/gif",
                    minImageWidth: 500,
                    maxsize: 200000,
                },
                image1:{
                    extension: "png|jpeg|jpg",
                    accept: "image/jpg,image/jpeg,image/png,image/gif",
                    maxsize: 200000,
                }
            },
            messages:{
                car_name:{
                    required:"Please Enter Name",
                },
                desc:{
                    required:"Please Enter Description ",
                },
              
                image:{
                    required:"Please Select Proper Image",
                    extension: "Invalid File Selection",
                    accept: "Invalid File Selection",
                    maxsize: "Please Select File Less Than 2-Mb",
                },
                image1:{
                    extension: "Invalid File Selection",
                    accept: "Invalid File Selection",
                    maxsize: "Please Select File Less Than 2-Mb",
                }
            }
        });
    });
</script>
<script>
    function deleteCar(input){
        var url = "{{route('admin.review.delete', ":id")}}";
        url = url.replace(':id', input);
        $.ajax({
            dataType: "json",
            type: "POST",
            url: url,
            data: {
                "_token": "{{ csrf_token() }}",
            },
            success: function (data) {
                location.reload();
            }
        });
    }
</script>